# Generated by Django 2.0.2 on 2018-03-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cyp.Faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cyp.University'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(to='cyp.Department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
